name: Rasa 

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  training-testing:
    name: Training and Testing
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: stockrecolib/chatbot
    steps:
      - uses: actions/checkout@v4
      - name: Rasa Train and Test GitHub Action
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          data_validate: true
          rasa_train: true
          cross_validation: true
          rasa_test: true
          train_args: '--domain stockrecolib/chatbot/domain.yml'
          test_type: all
          publish_summary: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload model
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@master
        with:
          name: model
          path: models